# Generated by Django 4.2 on 2025-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('value', models.CharField(max_length=100, verbose_name='القيمة')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='الأيقونة')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='اللون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('period', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('yearly', 'سنوي'), ('current', 'حالي')], default='monthly', max_length=20, verbose_name='الفترة')),
                ('type', models.CharField(choices=[('sales', 'مبيعات'), ('purchases', 'مشتريات'), ('inventory', 'مخزون'), ('finance', 'مالي'), ('customers', 'عملاء'), ('suppliers', 'موردين'), ('users', 'مستخدمين'), ('invoices', 'فواتير')], default='sales', max_length=20, verbose_name='النوع')),
                ('change_value', models.CharField(blank=True, max_length=20, null=True, verbose_name='قيمة التغيير')),
                ('change_type', models.CharField(choices=[('increase', 'زيادة'), ('decrease', 'نقصان'), ('no_change', 'لا تغيير')], default='no_change', max_length=20, verbose_name='نوع التغيير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إحصائية لوحة التحكم',
                'verbose_name_plural': 'إحصائيات لوحة التحكم',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('danger', 'خطر'), ('inventory_alert', 'تنبيه مخزون'), ('payment_received', 'دفعة مستلمة'), ('new_invoice', 'فاتورة جديدة'), ('return_request', 'طلب إرجاع')], default='info', max_length=20, verbose_name='النوع')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('data_type', models.CharField(choices=[('string', 'نص'), ('integer', 'عدد صحيح'), ('decimal', 'عدد عشري'), ('boolean', 'منطقي'), ('json', 'JSON'), ('date', 'تاريخ'), ('datetime', 'تاريخ ووقت')], default='string', max_length=20, verbose_name='نوع البيانات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('group', models.CharField(choices=[('general', 'عام'), ('finance', 'مالي'), ('inventory', 'مخزون'), ('sales', 'مبيعات'), ('purchases', 'مشتريات'), ('system', 'نظام')], default='general', max_length=20, verbose_name='المجموعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['group', 'key'],
            },
        ),
    ]
