# Generated by Django 4.2 on 2025-04-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_bankreconciliation'),
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='financial_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.transaction', verbose_name='المعاملة المالية'),
        ),
    ]
