# Generated by Django 4.2 on 2025-04-03 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسوية')),
                ('system_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='رصيد النظام')),
                ('bank_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='رصيد البنك')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الفرق')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='financial.account', verbose_name='الحساب')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تسوية بنكية',
                'verbose_name_plural': 'التسويات البنكية',
                'ordering': ['-reconciliation_date'],
            },
        ),
    ]
